# Generated by Django 3.0.7 on 2020-06-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='anoConclusao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='anoOcupacaoInicio',
        ),
    ]
