# Generated by Django 3.0.7 on 2020-07-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200629_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='anoConclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoal',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoal',
            name='site',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='anoOcupacaoInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
