# Generated by Django 3.0.7 on 2020-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200925_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='anoPerido',
            field=models.CharField(blank=True, choices=[('20201', '2020.1'), ('20202', '2020.2')], max_length=5, null=True),
        ),
    ]
