# Generated by Django 3.0.7 on 2020-07-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200713_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEgresso',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('dataNascimento', models.DateField(null=True)),
                ('pais', models.CharField(choices=[('BR', 'Brasil'), ('FR', 'França'), ('CA', 'Canadá')], max_length=2)),
                ('estado', models.CharField(choices=[('CE', 'Ceará'), ('RN', 'Rio Grando do Norte'), ('PE', 'Pernambuco'), ('RS', 'Rio Grande do Sul')], max_length=2)),
                ('cidade', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=13)),
                ('site', models.CharField(max_length=45, null=True)),
                ('curso', models.CharField(choices=[('BCC', 'Bach. Ciência da Computação'), ('PPGCC', 'Pós-Graduação em Ciência da Computação')], max_length=5)),
                ('anoConclusao', models.IntegerField(blank=True, null=True)),
                ('tituloTrabalho', models.CharField(max_length=100)),
                ('areaAtuacao', models.CharField(blank=True, max_length=50, null=True)),
                ('naturezaOcupacao', models.CharField(blank=True, choices=[('SP', 'Setor Público'), ('SP', 'Setor Privado'), ('TS', 'Terceiro Setor - organizações sem fins lucrativos'), ('PL', 'Profissional Liberal'), ('FL', 'Freelancer'), ('BT', 'Bolsista'), ('MT', 'Militar'), ('OI', 'Organismo Internacional')], max_length=2, null=True)),
                ('anoOcupacaoInicio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Academico',
        ),
        migrations.DeleteModel(
            name='Pessoal',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
    ]
