# Generated by Django 3.0.7 on 2020-09-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200925_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroegresso',
            old_name='anoPerido',
            new_name='anoPeriodo',
        ),
    ]
