# Generated by Django 3.0.7 on 2020-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200925_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroegresso',
            name='opcaoMercado',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
