# Generated by Django 3.0.7 on 2020-09-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200925_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='naturezaOcupacao',
        ),
        migrations.AddField(
            model_name='cadastroegresso',
            name='formaTrabalho',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
