# Generated by Django 3.0.7 on 2020-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200925_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='naturezaOcupacao',
        ),
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='tituloTrabalho',
        ),
        migrations.AddField(
            model_name='cadastroegresso',
            name='formaTrabalho',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroegresso',
            name='ingressoPos',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroegresso',
            name='outraFormacao',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroegresso',
            name='outraFormacaoInfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastroegresso',
            name='areaAtuacao',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
