# Generated by Django 3.0.7 on 2020-10-21 20:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201021_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroegresso',
            name='pais',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
