# Generated by Django 3.0.7 on 2020-10-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201020_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='dataNascimento',
        ),
    ]
