# Generated by Django 3.0.7 on 2020-09-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200925_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroegresso',
            name='outraFormacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastroegresso',
            name='outraFormacaoInfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
