# Generated by Django 3.0.7 on 2020-10-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cadastroegresso_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='pais',
            field=models.CharField(max_length=2),
        ),
    ]
