# Generated by Django 3.0.7 on 2020-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200928_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='outraFormacao',
            field=models.CharField(max_length=3),
        ),
    ]
