# Generated by Django 3.0.7 on 2020-10-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_cadastroegresso_datanascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='pais',
        ),
    ]
