# Generated by Django 3.0.7 on 2020-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200929_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='outraFormacao',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cadastroegresso',
            name='outraFormacaoInfo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
