# Generated by Django 3.0.7 on 2020-10-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cadastroegresso_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='ingressoPos',
            field=models.CharField(max_length=50),
        ),
    ]
