# Generated by Django 3.0.7 on 2020-10-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201020_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroegresso',
            name='pais',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
