# Generated by Django 3.0.7 on 2020-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200930_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='outraFormacao',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastroegresso',
            name='outraFormacaoInfo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
