# Generated by Django 3.0.7 on 2020-09-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200930_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='tituloTrabalho',
        ),
    ]
