# Generated by Django 3.0.7 on 2020-10-21 01:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cadastroegresso_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
