# Generated by Django 3.0.7 on 2020-10-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201020_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroegresso',
            name='pais',
        ),
    ]
