# Generated by Django 3.0.7 on 2020-10-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_cadastroegresso_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroegresso',
            name='areaAtuacao',
            field=models.CharField(max_length=20),
        ),
    ]
